bind=Ctrl,p,sendshortcut,,up,
bind=Ctrl,n,sendshortcut,,down,
bind=Ctrl,f,sendshortcut,,right,
bind=Ctrl,b,sendshortcut,,left,
bind=Alt,f,sendshortcut,Ctrl,right,
bind=Alt,b,sendshortcut,Ctrl,left,
bind=Ctrl,e,sendshortcut,,end,
bind=Ctrl,a,sendshortcut,,home,
bind=Ctrl,b,sendshortcut,,delete,
bind=Ctrl,h,sendshortcut,,backspace,
bind=Alt,d,sendshortcut,Ctrl,delete,
# Emacs like
bind=Ctrl,w,sendshortcut,Ctrl,x,
# Modeline like
# bind=Ctrl,w,sendshortcut,Ctrl,backspace,

bind=Ctrl,y,sendshortcut,Ctrl,v,
bind=Ctrl,slash,sendshortcut,Ctrl,z,

# Mark mode       
bind=Ctrl,space,submap,mark
                  
submap=mark       
bind=Ctrl,p,sendshortcut,Shift,up,
bind=Ctrl,n,sendshortcut,Shift,down,
bind=Ctrl,f,sendshortcut,Shift,right,
bind=Ctrl,b,sendshortcut,Shift,left,
bind=Alt,f,sendshortcut,CtrlShift,right,
bind=Alt,b,sendshortcut,CtrlShift,left,
bind=Ctrl,e,sendshortcut,Shift,end,
bind=Ctrl,a,sendshortcut,Shift,home,
bind=Alt,w,exec, hyprctl dispatch sendshortcut,Ctrl,c,; hyprctl dispatch submap reset
                  
#Cancel Mark Mode 
bind=Ctrl,g,submap,reset
submap=reset      
