# Or you can remove this an use emacs binds full time(not recommend)
bind = super, escape, submap, emacs_mode

submap = emacs_mode

# Word Movement
bind=Ctrl,p,sendshortcut,,up,
bind=Ctrl,n,sendshortcut,,down,
bind=Ctrl,f,sendshortcut,,right,
bind=Ctrl,b,sendshortcut,,left,

# Page Movement
bind=Ctrl,v,sendshortcut,,page_down,
bind=Alt,v,sendshortcut,,page_up,

# Buffer Movement
bind=Alt,f,sendshortcut,Ctrl,right,
bind=Alt,b,sendshortcut,Ctrl,left,

# Line
bind=Ctrl,e,sendshortcut,,end,
bind=Ctrl,a,sendshortcut,,home,

# Page Movement
bind=Alt Shift, comma,sendshortcut,Ctrl,home,
bind=Alt Shift, dot,sendshortcut,Ctrl,end,

# Delete
bind=Alt,d,sendshortcut,Ctrl,delete,
bind=Ctrl,b,sendshortcut,,delete,
bind=Alt,backspace,sendshortcut,Ctrl,backspace,

## Delete Line
bind=Ctrl,k,exec, hyprctl dispatch sendshortcut,Ctrl,x,

# Readline Ctrl-h
bind=Ctrl,h,sendshortcut,,backspace,

# Emacs Like
#bind=Ctrl, slash,sendshortcut,Ctrl,z,
# GTK Emacs binds like
bind=Ctrl, slash,sendshortcut,Ctrl,a,

# Kill Region
# bind=Ctrl,w,sendshortcut,Ctrl,x,  
# Readline like
bind=Ctrl,w,sendshortcut,Ctrl,backspace,
# Copy Region
bind=Alt,w,exec, hyprctl dispatch sendshortcut,Ctrl,c,; hyprctl dispatch submap emacs_mode

# Paste
bind=Ctrl,y,sendshortcut,Ctrl,v,

# Undo/Redo
bind=Ctrl,slash,sendshortcut,Ctrl,z,
bind=Ctrl Shift,minus,sendshortcut,Ctrl,z,

# Mark mode       
bind=Ctrl,space,submap,mark_mode
# Ctrl-x submap
bind=Ctrl,x,submap,Ctrl_x

# Alternative With Shift to the default movement keybinds

# Word Movement
bind=Ctrl Shift,p,sendshortcut,Shift,up,
bind=Ctrl Shift,n,sendshortcut,Shift,down,
bind=Ctrl Shift,f,sendshortcut,Shift,right,
bind=Ctrl Shift,b,sendshortcut,Shift,left,

# Page Movement
bind=Ctrl Shift,v,sendshortcut,Shift,page_down,
bind=Alt Shift,v,sendshortcut,Shift,page_up,

# Buffer Movement
bind=Alt Shift,f,sendshortcut,Ctrl Shift,right,
bind=Alt Shift,b,sendshortcut,Ctrl Shift,left,

# Line
bind=Ctrl Shift,e,sendshortcut,Shift,end,
bind=Ctrl Shift,a,sendshortcut,Shift,home,

# Exit Emacs Mode
bind = Super, escape, submap, reset
bind = Ctrl, g, submap, reset
submap=reset

submap=mark_mode

# Word Movement
bind=Ctrl,p,sendshortcut,Shift,up,
bind=Ctrl,n,sendshortcut,Shift,down,
bind=Ctrl,f,sendshortcut,Shift,right,
bind=Ctrl,b,sendshortcut,Shift,left,

# Page Movement
bind=Ctrl,v,sendshortcut,Shift,page_down,
bind=Alt,v,sendshortcut,Shift,page_up,

# Buffer Movement
bind=Alt,f,sendshortcut,Ctrl Shift,right,
bind=Alt,b,sendshortcut,Ctrl Shift,left,

# Line
bind=Ctrl,e,sendshortcut,Shift,end,
bind=Ctrl,a,sendshortcut,Shift,home,

# Page Movement
bind=Alt Shift, comma,sendshortcut,Ctrl Shift,home,
bind=Alt Shift, dot,sendshortcut,Ctrl Shift,end,

# Kill Region
bind=Ctrl,w,exec, hyprctl dispatch sendshortcut,Ctrl,x,; hyprctl dispatch submap emacs_mode
# Copy Region
bind=Alt,w,exec, hyprctl dispatch sendshortcut,Ctrl,c,; hyprctl dispatch submap emacs_mode

# Paste
bind=Ctrl,y,sendshortcut,Ctrl,v,

# Cancel Mark Mode
bind = Ctrl, g, submap, emacs_mode

submap=reset      

submap = Ctrl_x

# Save File
bind=Ctrl,s,exec, hyprctl dispatch sendshortcut,Ctrl,s,; hyprctl dispatch submap emacs_mode
# Find Files
bind=Ctrl,f,exec, hyprctl dispatch sendshortcut,Ctrl,o,; hyprctl dispatch submap emacs_mode
# Kill Buffer(Close Tab)
bind=,k,exec, hyprctl dispatch sendshortcut,Ctrl,w,; hyprctl dispatch submap emacs_mode
# Select All
bind=,h,exec, hyprctl dispatch sendshortcut,Ctrl,a,; hyprctl dispatch submap mark_mode

bind=,u,exec, hyprctl dispatch sendshortcut,Ctrl,y,; hyprctl dispatch submap emacs_mode
# bind=,u,exec, hyprctl dispatch sendshortcut,Ctrl Shift,z,; hyprctl dispatch submap emacs_mode

# Cancel Ctrl_x
bind=Ctrl,g,submap,emacs_mode
submap=reset
